# Generated by Django 4.0.6 on 2022-08-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=64)),
                ('email_to', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=32)),
                ('message', models.TextField(max_length=999)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DecimalField(decimal_places=8, max_digits=10)),
                ('request_method', models.CharField(max_length=32)),
                ('query_params', models.CharField(max_length=255)),
                ('ip_client', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=64)),
                ('source_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency_type', models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('KZH', 'Kazakh'), ('CZK', 'Czech crown'), ('JPY', 'Yen'), ('CHF', 'Swiss francs'), ('BTC', 'BitCoin')], default='USD', max_length=3)),
                ('currency_type', models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('KZH', 'Kazakh'), ('CZK', 'Czech crown'), ('JPY', 'Yen'), ('CHF', 'Swiss francs'), ('BTC', 'BitCoin')], default='UAH', max_length=3)),
                ('sale', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.source')),
            ],
        ),
    ]
