# Generated by Django 4.0.6 on 2022-07-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.DecimalField(decimal_places=4, max_digits=10)),
                ('email_from', models.EmailField(max_length=64)),
                ('email_to', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=32)),
                ('message', models.TextField(max_length=999)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
