# Generated by Django 4.0.6 on 2022-09-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(choices=[('PrivatBank', 'Private Bank')], max_length=16, unique=True),
        ),
    ]
