# Generated by Django 4.0.6 on 2022-10-02 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_created_alter_source_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
