# Generated by Django 4.0.6 on 2022-08-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='base_currency_type',
            field=models.CharField(choices=[
                ('UAH', 'Hryvnia'),
                ('USD', 'Dollar'),
                ('EUR', 'Euro'),
                ('KZH', 'Kazakh'),
                ('CZK', 'Czech crown'),
                ('JPY', 'Yen'),
                ('CHF', 'Swiss francs'),
                ('BTC', 'BitCoin')],
                default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.CharField(choices=[
                ('UAH', 'Hryvnia'),
                ('USD', 'Dollar'),
                ('EUR', 'Euro'),
                ('KZH', 'Kazakh'),
                ('CZK', 'Czech crown'),
                ('JPY', 'Yen'),
                ('CHF', 'Swiss francs'),
                ('BTC', 'BitCoin')],
                default='UAH', max_length=3),
        ),
    ]
