# Generated by Django 4.0.6 on 2022-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_rate_base_currency_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DecimalField(decimal_places=4, max_digits=10)),
                ('request_method', models.CharField(max_length=32)),
                ('query_params', models.CharField(max_length=255)),
                ('ip_client', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
