# Generated by Django 4.0.6 on 2022-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_responselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='response_time',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
